name : lab3 workflow
on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: checkouut repository
        uses: actions/checkout@v4

      - name: display message  
        run: echo "github actions executed successfully!"
      
