name: Lab3 Workflow
 
on:
  push:
    branches:
      - main
 
jobs:
  hello-world:
    runs-on: ubuntu-latest
 
    steps:
      - name: Print Message
        run: echo "GitHub Actions executed successfully!"
      
